#version: '2'
services:
  student_rpc:
    container_name: student_rpc
    build: python/
    restart: always
    depends_on:
      - db

    networks:
      - microservice_network
      - default
  
  db:
    container_name: student_mariadb
    image: mariadb
    restart: always
    volumes:
      - ./mariadb/initdb:/docker-entrypoint-initdb.d
      - ./mariadb/data:/var/lib/mysql
    
    environment:
      - MYSQL_ROOT_PASSWORD=devops101
      - MYSQL_DATABASE=devops_db
      - MYSQL_USER=devops
      - MYSQL_PASSWORD=devops101

  pma:
    container_name: student_phpmyadmin
    image:  phpmyadmin/phpmyadmin
    restart: always
    networks:
      - webproxy
      - default

    environment:
      - VIRTUAL_HOST=mydb.lab20.cpsudevops.com
    expose:
      - '80'

networks:
  default:
    external: true
    name: student_network

  microservice_network:
    external: true
    name: microservice_network

  webproxy:
    external: true
    name: webproxy